version: "3.7"

services:
  postgres:
    build:
      context: ../docker
      dockerfile: postgres.dockerfile
    container_name: "parser-postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    command: [ "postgres", "-c", "wal_level=logical" ]
    volumes:
      - ./db-parser-volume:/var/lib/postgresql/data